### ISSUE TITLE
Issue with Okta Verify Push Reject/Deny Response

### ISSUE THREAD

**Issue by HarshaVardhanAnde** [okta/okta-idx-dotnet#168]
### Describe the bug?

When user selects Okta Verify push and accepts the push request we are getting a proper response from PollAuthenticatorPushStatusAsync() sdk provided method but when push request is denied there is no return back(response) from PollAuthenticatorPushStatusAsync() API.

### What is expected to happen?

When user rejects/denied the push request we expect some response from PollAuthenticatorPushStatusAsync() API method like user denied the request and "continuepolling" value as false.

### What is the actual behavior?

When user denies the push request there is no response from PollAuthenticatorPushStatusAsync(). There is no exception/error as well. It is lost with no response even after timeout span.

### Reproduction Steps?

1. Perform primary authentication
2. Select Push factor - 
3. Send Push notification to user  - SelectChallengeAuthenticatorAsync() 
4. Upon getting the push request, reject the request from Okta verify application on mobile.
5. There is no response(get back) from polling - PollAuthenticatorPushStatusAsync();

### .NET Version

.NET Core 3.1

### SDK Version

Okta.Idx.Sdk 2.2.1 (latest dotnet sdk)

### OS version

Windows 11 : 

BuildNumber                   Caption                               OSArchitecture       Version
22000                     Microsoft Windows 11 Pro               64-bit                 10.0.22000

Windows 10 : 

BuildNumber                   Caption                              OSArchitecture       Version
19044                     Microsoft Windows 10 Pro                64-bit               10.0.19044

**Comment by bryanapellanes-okta** [comment]
@HarshaVardhanAnde Thanks for bringing this to our attention!  I've opened an internal ticket to address the issue, this will need to be prioritized with other work.

Internal Ref: OKTA-509595

**Comment by HarshaVardhanAnde** [comment]
Thank you @bryanapellanes-okta for your quick response.

**Comment by bryanapellanes-okta** [comment]
@HarshaVardhanAnde After some initial investigation I'd like to ensure we address the issue specifically as it relates to your scenario and configuration.  Please reach out to our support team at developers@okta.com - this will enable us to work with you directly and discuss details about your configuration in a less public manner; the support team will coordinate with the development team (me) to reproduce the issue and implement an appropriate fix.

**Comment by HarshaVardhanAnde** [comment]
@bryanapellanes-okta Sure thing, I will reach out to your support team. 
Thank you.
