### ISSUE TITLE
Issue with Phone factor when enrolled with multiple contact numbers

### ISSUE THREAD

**Issue by HarshaVardhanAnde** [okta/okta-idx-dotnet#169]
### Describe the bug?

If user is enrolled with multiple contacts for phone factor, In the primary authentication response  in "authenticators" list only one enrollment info is shown which is the first contact that user used for enrollment.

### What is expected to happen?

If User is enrolled with multiple phone numbers for phone factor in primary authentication responses we expect to get all enrollments info.

### What is the actual behavior?

If User is enrolled with multiple phone numbers, in the primary authentication response in "authenticators" list we get only one enrollment info for phone factor which is the first enrolled phone number.

### Reproduction Steps?

1.  Enroll with multiple phone number for phone factor in Okta.
2.  After primary authentication if you check "authenticators" in the primary authentication response we get only one enrollment 
3.  for phone factor which is the first enrolled phone number.  

### .NET Version

.NET Core 3.1

### SDK Version

Okta.Idx.Sdk 2.2.1 (latest dotnet sdk)

### OS version

Windows 11 : 

BuildNumber                   Caption                               OSArchitecture       Version
22000                     Microsoft Windows 11 Pro               64-bit                 10.0.22000

Windows 10 : 
BuildNumber          Caption                                       OSArchitecture              Version
19044                      Microsoft Windows 10 Pro               64-bit                            10.0.19044

**Comment by bryanapellanes-okta** [comment]
@amitSahu9 Thanks for bringing this to our attention! I've opened an internal ticket to address the issue, this will need to be prioritized with other work.

Internal Ref: OKTA-509616

**Comment by HarshaVardhanAnde** [comment]
Thank you @bryanapellanes-okta for your quick response.

**Comment by laura-rodriguez** [comment]
Fixed in 2.2.7
