### ISSUE TITLE
Issue with Number challenge in Okta Verify Push factor

### ISSUE THREAD

**Issue by amitSahu9** [okta/okta-idx-dotnet#170]
### Describe the bug?

The response from okta in Okta verify push is not properly handled in the SDK as a result the number verification is not working since we don't have that parameter in SDK to grab the correct answer.

### What is expected to happen?

There must be a parameter to grab the correct answer in case of push verification with number challenge.

### What is the actual behavior?

The actual behaviour right now is as if there is no number verification required.

### Reproduction Steps?

- perform primary authentication
- select Okta verify push factor
- hit send push api - SelectChallengeAuthenticatorAsync()
in the response that is processed by the SDK doesn't contain the correct answer parameter, which is needed for successful authentication, but as the parameter is not specified in the SDK , we are unable to fetch the value.

### .NET Version

.NET Core 3.1

### SDK Version

Okta IDX Sdk 2.2.1

### OS version

Windows 11 :
BuildNumber                             Caption                         OSArchitecture                      Version
22000                          Microsoft Windows 11 Pro                 64-bit                           10.0.22000

Windows 10 :
BuildNumber                             Caption                        OSArchitecture                       Version
19044                          Microsoft Windows 10 Pro                64-bit                            10.0.19044

**Comment by bryanapellanes-okta** [comment]
@amitSahu9 Thanks for your patience on this issue.  As we begin investigation, please reach out to developers@okta.com, I will coordinate with them while they work with you directly and discuss details about your configuration in a less public manner.
