### ISSUE TITLE
Issue with Send Push API

### ISSUE THREAD

**Issue by PranithaReddyAedla** [okta/okta-idx-dotnet#173]
### Describe the bug?

When "Send Push Automatically" is disabled in OKTA for Okta Verify factor, Send Push API is not sending the push notification to mobile app.

### What is expected to happen?

Irrespective of "Send Push Automatically" setting in OKTA, when user clicks send push button (use send push API - `SelectChallangeAuthenticatorAsync` and POLL API - `PollAuthenticatorPushStatusAsync`) a push notification should be sent to Okta verify mobile app and polling should start to identify users action

### What is the actual behavior?

Send Push notification is sent to Mobile only when "Send Push Automatically" is enabled in OKTA.

When "Send Push Automatically" is disabled, Send Push API is not delivering push notification to mobile app and polling API is throwing an exception.
```
Exception : Unexpected remediation step: Expected 'challenge-poll' but received ['authenticator-verification-data,select-authenticator-authenticate'].
Verify that your policies are configured as expected.
```

### Reproduction Steps?

1. Disable "Send Push Automatically" in Okta Web.
2. Use SDK and hit `SelectChallangeAuthenticatorAsync` and `PollAuthenticatorPushStatusAsync` for Okta Verify factor.
SelectChallangeAuthenticatorAsync - will not deliver push notification to user on app.
PollAuthenticatorPushStatusAsync - which start as soon as SelectChallangeAuthenticatorAsync is called, will throw mentioned exception.

### .NET Version

.NET Core 3.1

### SDK Version

Okta IDX Sdk 2.2.1

### OS version

Windows 11 :
BuildNumber Caption OSArchitecture Version
22000 Microsoft Windows 11 Pro 64-bit 10.0.22000

Windows 10 :
BuildNumber Caption OSArchitecture Version
19044 Microsoft Windows 10 Pro 64-bit 10.0.19044

**Comment by bryanapellanes-okta** [comment]
@PranithaReddyAedla Thanks for bringing this to our attention.  I've entered an internal issue for tracking, this will need to be prioritized with other work.

Internal Ref: OKTA-523367

**Comment by bryanapellanes-okta** [comment]
@PranithaReddyAedla Thanks for your patience on this issue. After some initial investigation I'd like to ensure we address the issue specifically as it relates to your scenario and configuration. Please reach out to our support team at developers@okta.com - this will enable us to work with you directly and discuss details about your configuration in a less public manner; the support team will coordinate with us, the development team, to reproduce the issue and implement an appropriate fix.

**Comment by bryanapellanes-okta** [comment]
This issue was auto closed by association.  I will comment here when the new nuget package is published, which should happen shortly.

**Comment by bryanapellanes-okta** [comment]
v2.2.4 is now published.
