### ISSUE TITLE
Reset password workflow fails on to SelectRecoveryAuthenticatorAsync with null reference exception

### ISSUE THREAD

**Issue by mgpartssource** [okta/okta-idx-dotnet#174]
### Describe the bug?

Preconditions: 
We're using our OIE instance at dev-auth.partssource.com
We use the self-hosted sign-in widget and the forgot password worfklow works as expected
We've verified the authenticator setup and the okta-idx-dotnet SDK configuration (endpoint, client id, etc)

Issue:
When initiating the forgot password workflow from the okta-id-dotnet SDK we receive a null reference exception on the call to to SelectRecoveryAuthenticatorAsync as outlined on the guide in step 5 here: https://developer.okta.com/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/aspnet/main/#_5-make-a-call-to-the-selectrecoveryauthenticatorasync-method

 

### What is expected to happen?

It is expected that the login id that initiates the recover password workflow will receive an email with a "magic" link to reset their password.  This works as expected in our test environment with the self-hosted sign-in widget.  This does not happen when the recover password workflow is initiated for the same user from the okta-idx-dotnet SDK.  

### What is the actual behavior?

When initiating the forgot password workflow from the okta-id-dotnet SDK we receive a null reference exception on the call to to SelectRecoveryAuthenticatorAsync as outlined on the guide in step 5 here: https://developer.okta.com/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/aspnet/main/#_5-make-a-call-to-the-selectrecoveryauthenticatorasync-method

![image](https://user-images.githubusercontent.com/29633927/186006253-2e7d3dd9-2e08-4ed3-a43e-94bc4d10341c.png)

![image](https://user-images.githubusercontent.com/29633927/186006295-ea5c6666-c3cd-4ef4-9a9e-78aa08f4df70.png)

### Reproduction Steps?

Follow steps 3 and 5 here https://developer.okta.com/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/aspnet/main/#_3-make-a-call-to-the-recoverpasswordasync-method

1. Make a call to the RecoverPasswordAsync method

![image](https://user-images.githubusercontent.com/29633927/186006626-a3e8b39d-75f1-412d-80c9-467282c7cce0.png)

2. Make a call to the SelectRecoveryAuthenticatorAsync method with the authenticator id from the "email" authenticator

![image](https://user-images.githubusercontent.com/29633927/186006823-5f00421e-4614-4bd1-9b78-2b123a68324f.png)

Observe the null reference exception.  We debugged through the source code and found that the property "currentEnrollment.recover" is null in "SelectRecoveryAuthenticatorAsync"

![image](https://user-images.githubusercontent.com/29633927/186007069-4fcd5e72-03cd-45b3-8d0a-fd0a8d31a3b7.png)

### .NET Version

dotnet --version
6.0.302

### SDK Version

okta-idx-dontnet v2.2.1

### OS version

Microsoft Windows 11 Pro
Version
10.0.22000

BuildNumber
22000

OSArchitecture
64-bit

**Comment by bryanapellanes-okta** [comment]
@mgpartssource Thanks for bringing this to our attention!  I've entered an internal ticket to address the issue; it will need to be prioritized against other work.

Internal Ref: OKTA-526746

**Comment by bryanapellanes-okta** [comment]
@mgpartssource  I apologize for the inconvenience and thank you for your patience while we review this issue!  After initial investigation I'd like to ensure we address the issue specifically as it relates to your scenario and configuration. Please reach out to our support team at developers@okta.com - this will enable us to work with you directly and discuss details about your configuration in a less public manner; the support team will coordinate with us, the development team, to reproduce the issue and implement an appropriate fix.

**Comment by laura-rodriguez** [comment]
Fixed in 2.2.7
