### ISSUE TITLE
In Password Expiry case, Password complexity and age values are missing/absent

### ISSUE THREAD

**Issue by PranithaReddyAedla** [okta/okta-idx-dotnet#180]
### Describe the bug?

When user is with password expiry status and authenticating with okta-idx-dotnet AuthenticateAsync() method where payload is 
{
      Username = "{{username}}",
      Password = "{{password}}",
};
Then sdk response is not having password complexity and age info. 

Okta idx dotnet SDK AuthenticateAsync() response : [https://jsonblob.com/1024684397433208832](https://jsonblob.com/1024684397433208832)
Okta browser response : [https://jsonblob.com/1024684397433208832](https://jsonblob.com/1024685620534198272)

Okta browser response is having password complexity and age values in its "currentAuthenticator" object where as okta idx dotnet  AuthenticateAsync() response having "CurrentAuthenticator" as null object.

![image](https://user-images.githubusercontent.com/78303749/200348512-cd772bf4-c924-4ec7-9e77-eb44327927d5.png)

### What is expected to happen?

Expecting password complexity and age related info in "CurrentAuthenticator" object when user is in password expiry state while authenticating with AuthenticateAsync() method of okta-idx-dotnet sdk with following payload
{
      Username = "{{username}}",
      Password = "{{password}}",
};

### What is the actual behavior?

"CurrentAuthenticator" object is null and password complexity, age related info is absent when user is in password expiry state while authenticating with AuthenticateAsync() method of okta-idx-dotnet sdk with following payload
{
      Username = "{{username}}",
      Password = "{{password}}",
};

![image](https://user-images.githubusercontent.com/78303749/200355446-79441c86-0ac7-48ce-9c6c-c219a26e4236.png)

### Reproduction Steps?

1. Make sure user password is expired in OKTA.
2. Execute AuthenticateAsync() method with 
{
      Username = "{{username}}",
      Password = "{{password}}",
}
3. In response, "CurrentAuthenticator" should have password related info and complexity, age info but in this case whole "CurrentAuthenticator" is null.

### .NET Version

.NET Core 3.1

### SDK Version

Okta IDX Sdk 2.2.1, Okta IDX Sdk 2.2.2, Okta IDX Sdk 2.2.3

### OS version

Windows 11 :
BuildNumber Caption OSArchitecture Version
22000 Microsoft Windows 11 Pro 64-bit 10.0.22000
Windows 10 :
BuildNumber Caption OSArchitecture Version
19044 Microsoft Windows 10 Pro 64-bit 10.0.19044

**Comment by bryanapellanes-okta** [comment]
@PranithaReddyAedla Thanks for bringing this to our attention!  I've added an internal issue to include the password complexity information in the relevant Sdk classes.  This needs to be prioritized against other work.

Internal Ref: OKTA-548954
