### ISSUE TITLE
Exception while authenticating with AuthenticateAsync() method in Password Warn scenario

### ISSUE THREAD

**Issue by PranithaReddyAedla** [okta/okta-idx-dotnet#182]
### Describe the bug?

In password warn scenario, when performing authentication with AuthenticateAsync() method with below payload experiencing following exception instead of response with "**AwaitingPasswordReset**" status.

**Payload for AuthenticateAsync()** 
{ 
"Username" : "{{username}}",
"Password" : "{{password}}"
}

**Exception** : {"Unexpected remediation step: Expected '['reenroll-authenticator or select-authenticator-enroll or select-authenticator-authenticate']' but received ['reenroll-authenticator-warning,skip'].\n Verify that your policies are configured as expected."}

OKTA browser response for respective case : https://jsonblob.com/1024693548733448192

### What is expected to happen?

Expecting a response with "**AwaitingPasswordReset**" status and user enrolled factors info.

### What is the actual behavior?

Getting exception when authenticating with AuthenticateAsync() sdk method in Password Warn state

### Reproduction Steps?

1. Make users' password to be in password warn state as per OKTA password policy.
2. Authenticate user with okta-idx-dotnet sdk method "AuthenticateAsync()" with payload having both username and password.
3. In response we get above stated exception instead of proper response with "AwaitingPasswordReset" status and user enrolled factors info.

### .NET Version

.NET Core 3.1

### SDK Version

Okta IDX Sdk 2.2.1, Okta IDX Sdk 2.2.2, Okta IDX Sdk 2.2.3

### OS version

Windows 11 :
BuildNumber Caption OSArchitecture Version
22000 Microsoft Windows 11 Pro 64-bit 10.0.22000
Windows 10 :
BuildNumber Caption OSArchitecture Version
19044 Microsoft Windows 10 Pro 64-bit 10.0.19044

**Comment by bryanapellanes-okta** [comment]
@PranithaReddyAedla Thank you for reporting this issue! I filed an internal ticket to be reviewed and prioritized by the team.

Internal Ref: OKTA-549674

**Comment by laura-rodriguez** [comment]
Fixed in 2.2.8
