### ISSUE TITLE
Issue with okta verify push authentication while having one/few required factors to enroll.

### ISSUE THREAD

**Issue by PranithaReddyAedla** [okta/okta-idx-dotnet#183]
### Describe the bug?

When the user is having one/few required factors to enroll and while user is authenticating with okta verify push factor using PollAuthenticatorPushStatusAsync() method for push polling, we expect required factors info and AwaitingAuthenticatorEnrollment status in response.

We are getting the expected "AwaitingAuthenticatorEnrollment" status, but "Authenticators"(required factor/factors info) object is null. This is happening only when authenticated with Okta-verify push and no issue when authenticaticating with other factors.

For example: Here, user is already enrolled for all the required factors except "Webauthn - Security Key or Biometric" factor. Below are the response when authenticated with push and phone factors in different attempts.

Okta-idx-dotnet SDK PollAuthenticatorPushStatusAsync() response for okta-verify push: https://jsonblob.com/1040245942158376960
Okta-idx-dotnet SDK VerifyAuthenticatorAsync() response for phone factor: https://jsonblob.com/1042350153918595072### 

### What is expected to happen?

- Expecting required factors info that needs to be enrolled in PollAuthenticatorPushStatusAsync() response for Authenticators key.

### What is the actual behavior?

Authenticators key is null

### Reproduction Steps?

1. User should have a required factor to be enrolled (which is not Okta verify) and the user should be enrolled for Okta verify.
2. Using okta-idx-dotnet sdk
i. Make primary authn using AuthenticationAsync()
ii. Send push using SelectChallengeAuthenticatorAsync()
iii. Poll for push authentication using PollAuthenticatorPushStatusAsync()
Once push is accepted by user, in response we expect AwaitingAuthenticatorEnrollment and factor details which is required and to be enrolled. But we are not getting required factor details with AwaitingAuthenticatorEnrollment status.

### .NET Version

.NET Core 3.1

### SDK Version

Okta IDX Sdk 2.2.1, Okta IDX Sdk 2.2.2, Okta IDX Sdk 2.2.3

### OS version

Windows 11 :
BuildNumber Caption OSArchitecture Version
22000 Microsoft Windows 11 Pro 64-bit 10.0.22000
Windows 10 :
BuildNumber Caption OSArchitecture Version
19044 Microsoft Windows 10 Pro 64-bit 10.0.19044

**Comment by bryanapellanes-okta** [comment]
@PranithaReddyAedla Thanks for bringing this to our attention! I apologize for the inconvenience.  I've entered an internal issue for tracking, this will need to be prioritized by the team.

Internal Ref: OKTA-55151
